# Generated by Django 6.0.2 on 2026-02-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_body_alter_post_slug_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
