name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install dependencies
        working-directory: image_viewer
        run: pip install -r requirements.txt

      - name: Check for errors
        working-directory: image_viewer
        env:
          DATABASE_URL: sqlite:///tmp/test.db  # use sqlite just for CI checks
        run: python manage.py check

      - name: Run tests
        working-directory: image_viewer
        env:
          DATABASE_URL: sqlite:///tmp/test.db
        run: python manage.py test

      - name: Trigger OpenShift build
        if: github.event_name == 'push' && success()  # only on push, not pull_request
        run: |
          curl -k -X POST \
            -H "Authorization: Bearer ${{ secrets.OKD_TOKEN }}" \
            -H "Content-Type: application/json" \
            https://api.okd.fured.cloud.bme.hu:6443/apis/build.openshift.io/v1/namespaces/endre-cloud-based-distributed-systems-laboratory/buildconfigs/my-app/instantiate \
            -d '{"kind":"BuildRequest","apiVersion":"build.openshift.io/v1","metadata":{"name":"my-app"}}'